name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Run Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: todos.martz.cloud
          username: root 
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/todos.martz.cloud
            git pull
            bun install
            bun run build
            pm2 restart ecosystem.config.cjs
